/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminInstagramConexaoRouteImport } from './routes/admin.instagram-conexao'
import { Route as AdminInstagramFunilRouteImport } from './routes/admin.instagram-funil'
import { Route as AdminInstagramFunilEditorFunnelIdRouteImport } from './routes/admin.instagram-funil-editor.$funnelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstagramConexaoRoute = AdminInstagramConexaoRouteImport.update({
  id: '/admin/instagram-conexao',
  path: '/admin/instagram-conexao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstagramFunilRoute = AdminInstagramFunilRouteImport.update({
  id: '/admin/instagram-funil',
  path: '/admin/instagram-funil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstagramFunilEditorFunnelIdRoute =
  AdminInstagramFunilEditorFunnelIdRouteImport.update({
    id: '/admin/instagram-funil-editor/$funnelId',
    path: '/admin/instagram-funil-editor/$funnelId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/instagram-conexao': typeof AdminInstagramConexaoRoute
  '/admin/instagram-funil': typeof AdminInstagramFunilRoute
  '/admin/instagram-funil-editor/$funnelId': typeof AdminInstagramFunilEditorFunnelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/instagram-conexao': typeof AdminInstagramConexaoRoute
  '/admin/instagram-funil': typeof AdminInstagramFunilRoute
  '/admin/instagram-funil-editor/$funnelId': typeof AdminInstagramFunilEditorFunnelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/instagram-conexao': typeof AdminInstagramConexaoRoute
  '/admin/instagram-funil': typeof AdminInstagramFunilRoute
  '/admin/instagram-funil-editor/$funnelId': typeof AdminInstagramFunilEditorFunnelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/instagram-conexao'
    | '/admin/instagram-funil'
    | '/admin/instagram-funil-editor/$funnelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/instagram-conexao'
    | '/admin/instagram-funil'
    | '/admin/instagram-funil-editor/$funnelId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/configuracoes'
    | '/admin/instagram-conexao'
    | '/admin/instagram-funil'
    | '/admin/instagram-funil-editor/$funnelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminInstagramConexaoRoute: typeof AdminInstagramConexaoRoute
  AdminInstagramFunilRoute: typeof AdminInstagramFunilRoute
  AdminInstagramFunilEditorFunnelIdRoute: typeof AdminInstagramFunilEditorFunnelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instagram-conexao': {
      id: '/admin/instagram-conexao'
      path: '/admin/instagram-conexao'
      fullPath: '/admin/instagram-conexao'
      preLoaderRoute: typeof AdminInstagramConexaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instagram-funil': {
      id: '/admin/instagram-funil'
      path: '/admin/instagram-funil'
      fullPath: '/admin/instagram-funil'
      preLoaderRoute: typeof AdminInstagramFunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instagram-funil-editor/$funnelId': {
      id: '/admin/instagram-funil-editor/$funnelId'
      path: '/admin/instagram-funil-editor/$funnelId'
      fullPath: '/admin/instagram-funil-editor/$funnelId'
      preLoaderRoute: typeof AdminInstagramFunilEditorFunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminInstagramConexaoRoute: AdminInstagramConexaoRoute,
  AdminInstagramFunilRoute: AdminInstagramFunilRoute,
  AdminInstagramFunilEditorFunnelIdRoute:
    AdminInstagramFunilEditorFunnelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
